name: 'Build Typebot'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          ${{ github.workspace }}/node_modules/playwright
        key: cache-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: cache-playwright-

    - if: steps.playwright-cache.outputs.cache-hit != 'true'
      name: Install playwright binaries
      shell: bash
      run: npx playwright install --with-deps

    - name: Build apps
      shell: bash
      run: pnpm run build:ci
